music.py: fix addition of song artist different from album artist
When adding a Various Artists album (or an album with guest artists)
where song artists are different from the album artist, the codepath
followed to add the artist if it's missing was broken:

  Traceback (most recent call last):
    File "jellyfin_kodi/objects/music.py", line 460, in song_artist_link
      temp_obj["ArtistId"] = self.jellyfin_db.get_item_by_id(
  TypeError: 'NoneType' object is not subscriptable

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "jellyfin_kodi/objects/music.py", line 467, in song_artist_link
      temp_obj["ArtistId"] = self.jellyfin_db.get_item_by_id(
    TypeError: 'NoneType' object is not subscriptable

Passing the library used for the song when trying to fetch the artist
so that it's used fixes this for me.

Fixes #913 and #837